CREATE DATABASE `odontokids`;
USE `odontokids`;

CREATE TABLE `responsavel` (
	`Id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`nome` VARCHAR(80) NOT NULL,
	`email` VARCHAR(150) NOT NULL,
	`cpf` VARCHAR(11) NOT NULL,
	`telefone` VARCHAR(11) NOT NULL,
	`nasc` DATE NOT NULL,
	`genero` VARCHAR(30) NOT NULL,
	`senha` VARCHAR(80) NOT NULL,
	PRIMARY KEY(`Id`)
);


CREATE TABLE `dependentes` (
	`id_responsavel` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`nome` VARCHAR(80) NOT NULL,
	`nasc` DATE NOT NULL,
	`cpf` VARCHAR(11) NOT NULL,
	`id` INTEGER NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE `consulta` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`horario` TIME NOT NULL,
	`data` DATE NOT NULL,
	`id_dependente` INTEGER NOT NULL,
	`cod_tratamento` INTEGER NOT NULL,
	`relatorio` VARCHAR(500) NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE `prontuario` (
	`id_consulta` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`arquivo_prontuario` BLOB
);


CREATE TABLE `tratamento` (
	`Id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Tratamento` VARCHAR(50) NOT NULL,
	`Descricao` VARCHAR(200) NOT NULL,
	PRIMARY KEY(`Id`)
);


CREATE TABLE `medico_tratamento` (
	`Id_tratamento` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`id_medico` INTEGER NOT NULL
);


CREATE TABLE `medico` (
	`Id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`nome` VARCHAR(80) NOT NULL,
	`email` VARCHAR(150) NOT NULL,
	`cpf` VARCHAR(11) NOT NULL,
	`telefone` VARCHAR(11) NOT NULL,
	`nasc` DATE NOT NULL,
	`genero` VARCHAR(50) NOT NULL,
	`senha` VARCHAR(70) NOT NULL,
	`CRM` VARCHAR(6) NOT NULL,
	`cod_especialidade` INTEGER NOT NULL,
	PRIMARY KEY(`Id`)
);


CREATE TABLE `especialidade` (
	`Id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`funcao` VARCHAR(50) NOT NULL,
	`descricao` VARCHAR(200) NOT NULL,
	PRIMARY KEY(`Id`)
);


ALTER TABLE `responsavel`
ADD FOREIGN KEY(`Id`) REFERENCES `dependentes`(`id_responsavel`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `dependentes`
ADD FOREIGN KEY(`id`) REFERENCES `consulta`(`id_dependente`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `consulta`
ADD FOREIGN KEY(`id`) REFERENCES `prontuario`(`id_consulta`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `tratamento`
ADD FOREIGN KEY(`Id`) REFERENCES `consulta`(`cod_tratamento`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `tratamento`
ADD FOREIGN KEY(`Id`) REFERENCES `medico_tratamento`(`Id_tratamento`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `medico`
ADD FOREIGN KEY(`Id`) REFERENCES `medico_tratamento`(`id_medico`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `especialidade`
ADD FOREIGN KEY(`Id`) REFERENCES `medico`(`cod_especialidade`)
ON UPDATE NO ACTION ON DELETE NO ACTION;